### ISSUE TITLE
没法下载了

### ISSUE THREAD

**Issue by k-basara** [Streamlet/MSPYForever#3]
下载地址都显示502 Bad Gateway，麻烦修复一下，谢谢了。

**Comment by Streamlet** [comment]
> 下载地址都显示502 Bad Gateway，麻烦修复一下，谢谢了。

https://streamlet.org/software/mspyforever/
应该可以了，试试？

**Comment by k-basara** [comment]
> > 下载地址都显示502 Bad Gateway，麻烦修复一下，谢谢了。
> 
> https://streamlet.org/software/mspyforever/ 应该可以了，试试？

可以下载了，谢谢。
